language: scala
scala:
   - 2.10.6

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION --warn "compile test:compile"
  - sbt ++$TRAVIS_SCALA_VERSION "test scripted"

sudo: false
cache:
 directories:
 - $HOME/.sbt
 - $HOME/.ivy2
